import type {Metadata} from "next";
import "./globals.css";
import {Header} from "@/app/ui/header/Header";
import {AuthProvider} from "@/app/lib/context/UserContext";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <AuthProvider>

            <html lang="en">
            <body
                className={`bg-[#EDEDED] p-4`}
            >
            <Header/>
            <main className={'container md:max-w-[80vw] md:mx-auto'}>
                {children}
            </main>
            </body>
            </html>
        </AuthProvider>

    );
}
